import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../components/layout/Header";
import { Sidebar } from "@/components/ui/sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const storesResponse = await fetch(
    `${process.env.NEXT_PUBLIC_URL}/api/get-stores`,
    {
      method: "GET",
      cache: "no-store",
    }
  );
  const { stores } = await storesResponse.json();

  const storesBasicInfo = stores.map(
    (store: { location: string; utm_source: string; utm_term: string }) => ({
      location: store.location,
      utm_source: store.utm_source,
      utm_term: store.utm_term,
    })
  );

  const collectionsResponse = await fetch(
    `${process.env.NEXT_PUBLIC_URL}/api/get-collections-ticketslist`,
    {
      method: "GET",
      cache: "no-store",
    }
  );
  const { collections } = await collectionsResponse.json();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col overflow-hidden`}
      >
        <Header />
        <div className="flex">
          <Sidebar stores={storesBasicInfo} collectionsTickets={collections} />
          <main className="flex-1 overflow-auto">
            <div className="h-screen backdrop-blur-sm bg-black/20 relative">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}

export default RootLayout;
